kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack-sa-25
      group_wait: 10s
      repeat_interval: 1m
 
    receivers:
    - name: slack-sa-25
      slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: '# test-notifications-1'

