on:
  workflow_dispatch:
    inputs:
      user: 
        description: "Requested user"
        required: true
env:
  fqdn: jenkins.k8s-9.sa
  ip: 178.124.206.53
  jenkins_url: http://jenkins.k8s-9.sa/job/test-user//buildWithParameters

jobs:
  run-jenkins-job:
    runs-on: ubuntu-latest
    steps: 
      - run: sudo apt update & sudo apt install curl
      - run: sudo echo "${{ env.ip }} ${{ env.fqdn }}" >> /etc/hosts
      - run: curl -X POST -u "${{ secrets.API_TOKEN }}" -d "token=${{ secrets.BUILD_TOKEN }}" -d "TESTED_USER=${{ inputs.user }}" http://jenkins.k8s-9.sa/job/test-user/buildWithParameters
