apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: sealed-secrets
    helm:
      values: |-
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.3
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
